### ISSUE TITLE
Remove "Season Pass" button and functionality from Radarr

### ISSUE THREAD

**Issue by evulhotdog** [galli-leo/Radarr#95] opened 2017-01-10 14:07 UTC
![image](https://cloud.githubusercontent.com/assets/365456/21809082/30139166-d714-11e6-8a7f-c6c77fce17d8.png)

**Comment by galli-leo** [comment] 2017-01-10 14:17
We have to fix the whole wanted tab anyway. Duplicate of #31.

**Closed by galli-leo** 2017-01-10 14:17 UTC
