### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by AcidRain999** [galli-leo/Radarr#72] opened 2017-01-09 02:56 UTC
when im importing my database why cant it search with the periods already removed? i have to manually goto each one and remove the periods between words just to have it find a match

**Comment by fedoranimus** [comment] 2017-01-09 03:18
I assume you meant "...without the periods already removed". The parser for library import is not complete and is going through an overhaul right now to support movies.

**Comment by fedoranimus** [comment] 2017-01-09 03:22
Duplicate of #65

**Closed by fedoranimus** 2017-01-09 03:22 UTC
Labels: bug, question
