### ISSUE TITLE
Movies do not show under the wanted screen

### ISSUE THREAD

**Issue by evulhotdog** [galli-leo/Radarr#98] opened 2017-01-10 15:05 UTC
I have movies that are not grabbed, but they do not show in the list.
Should probably link to #31 

![image](https://cloud.githubusercontent.com/assets/365456/21811032/18673c0e-d71c-11e6-8043-9a3bbbc74670.png)

![image](https://cloud.githubusercontent.com/assets/365456/21811098/57d2ddbc-d71c-11e6-8087-9e45e24a9348.png)

**Comment by galli-leo** [comment] 2017-01-10 15:06
Duplicate of #31

**Closed by galli-leo** 2017-01-10 15:06 UTC
